ifstream archivo8("perros.dat", ios::binary);
    // pair<string, perro *> par6;
    // pair<string, perro *> par7;
    // pair<string, perro *> par8;
    // pair<string, perro *> par9;
    // pair<string, perro *> par10;
    // archivo8.read((char *)&par6, sizeof(par6));
    // archivo8.read((char *)&par7, sizeof(par7));
    // archivo8.read((char *)&par8, sizeof(par8));
    // archivo8.read((char *)&par9, sizeof(par9));
    // archivo8.read((char *)&par10, sizeof(par10));
    // archivo8.close();